version: "3.6"

services:
  mongo:
    image: mongo
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
      DB_URL: ${DB_URL}
    volumes:
      - ./geoguessr:/usr/local/geoguessr
      - db-data:/data/db
    working_dir: /usr/local/geoguessr

  db:
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
      POSTGRES_DB: app
    volumes:
      - pg-data:/var/lib/postgresql/data

  server:
    image: node
    ports:
      - 3000:3000
    environment:
      DB_URL: ${DB_URL}
      PORT: 3000
      DATABASE_URL: ${DATABASE_URL}
      JWT_SECRET: ${JWT_SECRET}
      STRIPE_SECRET_KEY: ${STRIPE_SECRET_KEY}
      SENDINBLUE_API_KEY: ${SENDINBLUE_API_KEY}
      GOOGLE_CALLBACK : ${GOOGLE_CALLBACK}
      GOOGLE_CLIENT_SECRET : ${GOOGLE_CLIENT_SECRET}
      GOOGLE_CLIENT_ID : ${GOOGLE_CLIENT_ID}
    working_dir: /usr/src/app
    volumes:
      - ./server:/usr/src/app
    command: npm run dev
  adminer:
    image: adminer
    ports:
      - 8080:8080
    environment:
      ADMINER_DEFAULT_SERVER: db
      
volumes:
  db-data:
  pg-data:

