
name: Node.js CI

on:
  push:
    branches: [ "main", "feature/unit-testing" ]
  pull_request:
    branches: [ "main" , "feature/unit-testing"]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: cd server
    - run: npm ci
    - run: npm run build --if-present
    - run: npm run test
