name: Run Tests

on:
  push:
    branches:
      - dev 
      - feature/unit-testing
jobs:
  test:
    runs-on: ubuntu-latest  
    steps:
      - name: Checkout code
        uses: actions/checkout@v2 

      - name: Setup Node.js and run tests
        uses: actions/setup-node@v2
        
      - working-directory: ./server
        run : |
          run: npm install 
          run: npm test  
